@startuml

title Raft

participant "Follow" as f
participant "Candidate" as c
participant "Leader" as l

autonumber

f -> f: wait for election timeout
l -> f: heartbeat(term,logs[])
f -> f: reset election timeout
l -> l: dead...
f -> f: wait for election timeout
f -[#red]> c: transition to candidate

@enduml
